### PR TITLE
CashRegister-_App

### PR DESCRIPTION
**Pull request by Marwa-Sadat**
1.	🛠 Initialization: A class for the cash register has been created, initializing it with properties like totalAmount and itemList.
	2.	🛒 Add Items: A method to add items to the register has been implemented, updating the total amount and item list accordingly.
	3.	🗑 Remove Items: Functionality to remove items has been added, ensuring the total amount and item list are accurately adjusted.
	4.	💸 Apply Discounts: A method to apply discounts to the total amount has been created, supporting both percentage and fixed amount discounts.
	5.	🧾 Generate Receipt: A feature to print a detailed receipt has been developed, listing all items, their prices, and the final total amount after discounts.

### CODE REVIEW

**Comment by Marwa-Sadat** [comment]
@zainabbehzad
Hello Zainab, I hope you are well, please check my project.

**Comment by Marwa-Sadat** [comment]
@zainabbehzad
Hello Zainab, I hope you are well, please check my project.
Screenshot 2024-07-10 082704

**Review by zainabbehzad — APPROVED** [review]
@Marwa-Sadat 

🎉 Great Design Implemented
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Cash Register App project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your design is responsive
✔Your repo has a professional README.md file
* Please do not forget to add Deployment Link of your project in README.md

**Comment by Marwa-Sadat** [comment]
@ahzamir Hello sir I hope you are well, please check my project.

**Review by ahzamir — APPROVED** [review]
### Hi @Marwa-Sadat 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Cash Register project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

**Comment by Marwa-Sadat** [comment]
@ahzamir thank you so much dear sir😊

**Pull request merged**
